version: '3.3'
services:
  web:
    build: .
    command: python /code_elearning/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code_elearning
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=elearning"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"